name: wakeonlan

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: wakecli
    container_name: wakecli
    networks:
      - default
    stdin_open: true
    tty: true
    develop:
      watch:
        - action: rebuild
          path: .

  # manager:
  #   extends:
  #     service: client
  #   command: ["./wakeonlan", "manager"]
  #   hostname: wakemgr
  #   container_name: wakemgr
  
  # client1:
  #   extends:
  #     service: client
  #   hostname: wakecli1
  #   container_name: wakecli1

  # manager:
  #   extends:
  #     service: client
  #   command: ["/bin/bash"]
  #   hostname: wakemgr
  #   container_name: wakemgr


networks:
  default:
    driver: bridge